services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./.postgres.env

  postgres:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./.postgres.env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
